CREATE TABLE IF NOT EXISTS store_details(
    STORE_ID VARCHAR NOT NULL,
    STORE_LOCATION VARCHAR NOT NULL,
    PRODUCT_CATEGORY VARCHAR NOT NULL,
    PRODUCT_ID REAL NOT NULL,
    MRP REAL NOT NULL,
    CP REAL  NOT NULL,
    DISCOUNT REAL NOT NULL,
    SP REAL NOT NULL,
    DATE_ADDED date NOT NULL
);